### ISSUE TITLE
Failing to sort non-semver

### ISSUE THREAD

**Issue by kormide** [bazel-contrib/publish-to-bcr#97]
Stack trace from logs:
```
Invalid Version: 1.0.0rc1
TypeError: Invalid Version: 1.0.0rc1
    at new SemVer (/layers/google.nodejs.yarn/yarn_modules/node_modules/semver/classes/semver.js:38:13)
    at compare (/layers/google.nodejs.yarn/yarn_modules/node_modules/semver/functions/compare.js:3:3)
    at Array.sort (<anonymous>)
    at MetadataFile.sortVersions (file:///src/domain/metadata-file.ts:147:17)
    at new MetadataFile (file:///src/domain/metadata-file.ts:65:10)
    at updateMetadataFile (file:///src/domain/create-entry.ts:240:25)
    at CreateEntryService.createEntryFiles (file:///src/domain/create-entry.ts:69:5)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ReleaseEventHandler.attemptPublish (file:///src/application/release-event-handler.ts:208:7)
    at ReleaseEventHandler.handle (file:///src/application/release-event-handler.ts:94:29)
```

Caused by release: https://github.com/MobileNativeFoundation/rules_xcodeproj/releases/tag/1.14.0

`1.0.0rc1` is not a valid semver, however when versions are sorted the `semver` package seems to think it's valid and includes it for sorting, but then fails when actually trying to sort it.

**Comment by kormide** [comment]
Filed a bug on the `semver` project: https://github.com/npm/node-semver/issues/672
